name: HSE Mlops Git CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [ 3.10.12 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint mypy lxml pylint-report flake8-html
          poetry install --without dev  --without test  --no-interaction --no-ansi

      - name: Create directories
        run: |
          mkdir -p reports/triton_inference/flake8/
          mkdir -p reports/triton_inference/pylint/
          mkdir -p reports/triton_inference/mypy/

      - name: Check typing with mypy
        run: |
          mypy --html-report reports/triton_inference/mypy/ ./triton_inference || true

      - name: Lint with flake8
        run: |
          flake8 triton_inference || flake8 triton_inference --format=html --htmldir=reports/triton_inference/flake8/

      - name: Lint with pylint
        run: |
          pylint triton_inference || pylint triton_inference--output-format=pylint_report.CustomJsonReporter --load-plugins = "pylint_report"  | pylint_report > reports/triton_inference/pylint/report.html | false


      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: html_reports
          path: reports/
